/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import BatallaEvents.BatallaListener;
import BatallaEvents.ResultadoDisparoEvent;
import Models.Tablero;

/**
 *
 * @author MIRKO
 */
public class BatallaView extends javax.swing.JDialog implements BatallaListener{
    int contrincante_session_id;
    String contrincante_nick;
    MainForm parent;
    Tablero tablero;
    /**
     * Creates new form BatallaView
     */
    public BatallaView(java.awt.Frame parent, boolean modal, int contrincante_session_id, String contrincante_nick) {
        super(parent, modal);
        initComponents();
        
        this.contrincante_session_id = contrincante_session_id;
        this.contrincante_nick = contrincante_nick;
        this.parent = (MainForm)parent;
        tablero = new Tablero();
        this.parent.addBatallaListener(this);
        this.setTitle("Contrincante : " + contrincante_nick);
        this.text_area_tablero.setText(tablero.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text_area_tablero = new javax.swing.JTextArea();
        input_text_fila = new javax.swing.JTextField();
        input_text_columna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boton_disparar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        text_area_tablero.setColumns(20);
        text_area_tablero.setRows(5);
        jScrollPane1.setViewportView(text_area_tablero);

        input_text_fila.setText("0");
        input_text_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_text_filaActionPerformed(evt);
            }
        });

        input_text_columna.setText("0");

        jLabel1.setText("Fila");

        jLabel2.setText("Columna");

        boton_disparar.setText("Disparar");
        boton_disparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_dispararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_text_columna)
                            .addComponent(input_text_fila)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boton_disparar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_text_fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_text_columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_disparar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_text_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_text_filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_text_filaActionPerformed

    private void boton_dispararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_dispararActionPerformed
        int fila = Integer.parseInt(input_text_fila.getText());
        int columna = Integer.parseInt(input_text_columna.getText());
        this.parent.dispararA(contrincante_session_id, fila, columna);
    }//GEN-LAST:event_boton_dispararActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_disparar;
    private javax.swing.JTextField input_text_columna;
    private javax.swing.JTextField input_text_fila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text_area_tablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onResultadoDisparo(ResultadoDisparoEvent event) {
        System.out.println(event.getResultado());
    }
}
