/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import BatallaEvents.BatallaListener;
import ClienteSocket.ClienteTCP;
import ViewEvents.ConnectedEvent;
import ViewEvents.CrearTableroEvent;
import ViewEvents.ReconnectedEvent;
import ViewEvents.ResultadoDisparoEvent;
import ViewEvents.SalaEsperaEvent;
import ViewEvents.StartBatallaEvent;
import ViewEvents.TryConnectionEvent;
import ViewEvents.ViewListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.EventListenerList;
import utils.Parse;

/**
 *
 * @author MIRKO
 */
public class MainForm extends javax.swing.JFrame implements ViewListener{
    ClienteTCP cliente;
    /**
     * Creates new form Main
     */
    Timer timer = this.getTimer();
    int tictac = 0;
    char tipo;
    public MainForm() {
        initComponents();
        cliente = new ClienteTCP("127.0.0.1", 5000);
        cliente.addSocketListener(this);
    }
    
    public String registrarUsuario(String nick, String password){
        String respuesta = this.cliente.registrarUsuario(nick, password);
        HashMap<String, String> info = (HashMap<String, String>) Parse.convertMessageToInfo(respuesta);
        if(info.containsKey("COD") && info.get("COD").equals("200")){
            this.cliente.setNick(nick);
            this.cliente.startReadingMessage();
        }
        return respuesta;
    }
    
    public String loggearUsuario(String nick, String password){
        String respuesta = this.cliente.loggearUsuario(nick, password);
        HashMap<String, String> info = (HashMap<String, String>) Parse.convertMessageToInfo(respuesta);
        if(info.containsKey("COD") && info.get("COD").equals("200")){
            this.cliente.setNick(nick);
            this.cliente.startReadingMessage();
        }
        return respuesta;
    }
    public void loginExitoso(){
        user_name.setText("Usuario logueado : "+this.cliente.nick);
        mensaje.setText("Logueado exitosamente");
    }
    public void colocarBarco(int fil, int col, int size, char orientacion){
        this.cliente.colocarBarco(fil, col, size, orientacion);
    }
    public void entrarSalaEspera(){
        this.cliente.entrarSalaEspera();
    }
    public void dispararA(int contrincante_session_id, int fila, int columna){
        this.cliente.dispararA(contrincante_session_id, fila, columna);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        user_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(user_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.cliente.crearTablero();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    
    private Timer getTimer(){
        return new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(tipo == 'C') animacionTryConnect();
                else if(tipo == 'S') animacionSalaEspera();
                if(tictac < 4)tictac++;
                else tictac = 0;
            }
        });
    }
    private void animacionTryConnect(){
        if(tictac == 0 )mensaje.setText("Intentando contectar al servidor");
        else mensaje.setText(mensaje.getText()+" . ");
    }
    private void animacionSalaEspera(){
        if(tictac == 0 )mensaje.setText("Esperando mas jugadores");
        else mensaje.setText(mensaje.getText()+" . ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onConnected(ConnectedEvent event) {
        timer.stop();
        this.mensaje.setText("conectado al servidor");
        
        RegView registro = new RegView(this, true);
        registro.setVisible(true);
    }

    @Override
    public void onReconnected(ReconnectedEvent event) {
        timer.stop();
        String respuesta = this.cliente.reconectar();
        HashMap<String, String> info = (HashMap<String, String>) Parse.convertMessageToInfo(respuesta);
        this.mensaje.setText(info.get("MSJ"));
        
        this.cliente.startReadingMessage();
    }
    
    @Override
    public void onTryConnection(TryConnectionEvent event) {
        this.tipo = 'C';
        this.tictac = 0;
        if(timer.isRepeats() || timer.isRunning()) timer.restart();
        else timer.start();
    }
    @Override
    public void onCrearTablero(CrearTableroEvent event) {
        int dim = event.getDimencion();
        CrearTablero crearTablero = new CrearTablero(this, true, dim);
        crearTablero.setTitle("Tablero de " + cliente.nick);
        crearTablero.setVisible(true);
    }

    @Override
    public void onStartBatalla(StartBatallaEvent event) {
        String contrincante_nick = event.getContrincante_nick();
        int contrincante_session_id = event.getContrincante_session_id();
        BatallaView batalla = new BatallaView(this, true, contrincante_session_id, contrincante_nick);
        batalla.setVisible(true);
    }

    @Override
    public void onSalaEspera(SalaEsperaEvent event) {
        this.tipo = 'S';
        this.tictac = 0;
        if(timer.isRepeats() || timer.isRunning()) timer.restart();
        else timer.start();
    }

    @Override
    public void onResultadoDisparo(ResultadoDisparoEvent event) {
        BatallaEvents.ResultadoDisparoEvent batalla_events = new BatallaEvents.ResultadoDisparoEvent(event.getResultado(), event.getX(),event.getY(),this);
        this.notifyResultadoDisparoEvent(batalla_events);
    }
    /*------------------------------------------------------------------------*/
    protected EventListenerList listenerList = new EventListenerList();
    
    public void addBatallaListener(BatallaListener listener){
        listenerList.add(BatallaListener.class, listener);
    }
    public void removeBatallaListener(BatallaListener listener){
        listenerList.remove(BatallaListener.class, listener);
    }
    public void notifyResultadoDisparoEvent(BatallaEvents.ResultadoDisparoEvent event){
        Object[] listeners = listenerList.getListenerList();
        for (int i = 0; i < listeners.length; i = i + 2) {
            if(listeners[i] == BatallaListener.class){
                ((BatallaListener) listeners[i+1]).onResultadoDisparo(event);
            }
        }
    }
}
